### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [gnitetsky/kinozal-template-init-project#1]
![image](https://user-images.githubusercontent.com/8464662/54495368-e8195700-48eb-11e9-8ecb-e72606197f8a.png)
1 - радиусы
2 - отступы справа при отсутствии слева
3 - отступы снизу
4 - отступы сверху
5 - отступы слева при отсутствии справа

![image](https://user-images.githubusercontent.com/8464662/54495436-4f370b80-48ec-11e9-9721-74a30b2aed40.png)
мусор

![image](https://user-images.githubusercontent.com/8464662/54495465-ad63ee80-48ec-11e9-848b-34fa2b16e618.png)
селекторы уровнем более 2 обычно запрещаются в постановке задачи.

**Comment by gnitetsky** [comment]
fixed navbar-header and fixed selector levels
